# Generated by Django 2.0.4 on 2018-04-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJ_User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, null=True, unique=True)),
                ('password', models.CharField(max_length=32, null=True)),
                ('sex', models.CharField(default='1', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('head_img', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
