# Generated by Django 2.0.4 on 2018-04-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dj_user',
            options={'ordering': ['create_date'], 'verbose_name': '用户', 'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterModelTable(
            name='dj_user',
            table='D_USER',
        ),
    ]
