# Generated by Django 2.0.4 on 2018-04-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0002_auto_20180424_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj_user',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='dj_user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
