# Generated by Django 2.0.4 on 2018-04-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_content', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'S_Detail',
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=64)),
                ('shop_title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'S_User',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Shop_User',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='Shop_User_usernam_8785da_idx'),
        ),
        migrations.AddIndex(
            model_name='shopinfo',
            index=models.Index(fields=['shop_name', 'shop_title'], name='S_User_shop_na_625189_idx'),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='shop_info',
            field=models.OneToOneField(db_column='uid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='day02.ShopInfo'),
        ),
    ]
