# Generated by Django 2.0.4 on 2018-04-26 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('shop_info', models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='day02.ShopInfo')),
            ],
            options={
                'db_table': 'shop_car',
            },
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='shop_info',
            field=models.OneToOneField(db_column='shop_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='day02.ShopInfo'),
        ),
        migrations.AddIndex(
            model_name='shopcar',
            index=models.Index(fields=['shop_info'], name='shop_car_shop_id_e16b3c_idx'),
        ),
    ]
